from .languages import LANGUAGES

from .user_texts import EXPERIENCE, WEEK_DAY, CHOOSE_DAY, CHOOSE_TIME, R_MENU, COMMAND_TEXT, MIDDLEWARE_TEXT,\
    A_SETTINGS, R_SETTINGS, COMMON_TEXT, REGISTRATION, FUNCTION_TEXT, A_MENU

from .admin_texts import CONSOLE_TEXT, FOR_ADMINS